JSON exercise
consta35/SB pull request #1
Opened 2017-02-21 02:49 UTC by consta35

2017-02-21 03:17 UTC, amirziai requested changes
Looks pretty good 👍 

Added a couple of comments.

2017-02-21 03:17 UTC, amirziai commented on json_exerciseAnswers.ipynb
> +    "dfs['name'].replace('', np.nan, inplace=True)\n",
Using `inplace` is not a good idea, always try to [avoid it](http://stackoverflow.com/questions/22532302/pandas-peculiar-performance-drop-for-inplace-rename-after-dropna).

2017-02-21 03:17 UTC, amirziai commented on json_exerciseAnswers.ipynb
> +    "fill = dfs.fillna(method = 'ffill')\n",
Is [this](https://gist.github.com/amirziai/f29686ab7d8d2da70d1020e34609f0f3) helpful?

2017-02-21 03:17 UTC, amirziai commented on json_exerciseAnswers.ipynb
> +    "data = json.load((open('data/world_bank_projects.json')))\n",
A general point:
[DRY](https://www.wikiwand.com/en/Don't_repeat_yourself) is a very useful concept in software development. Every time you write something more than once you should think about it. It's easy to overdo it too so don't worry about it for this exercise but just be aware of its existence.

2017-02-23 02:27 UTC, amir-ziai-zefr commented
You're joining the dataframe with itself, which is not giving you any new information.

As you suggested you need to create a lookup table that maps codes to names. One way to do it is:
`df[df.name.str.len() > 0].groupby(['code']).first().reset_index()`.

Does that make sense? Can you now get the final answer? Is this efficient?

2017-02-23 02:30 UTC, amir-ziai-zefr commented
Also take a look at [drop_duplicates](http://pandas.pydata.org/pandas-docs/version/0.17.1/generated/pandas.DataFrame.drop_duplicates.html)

2017-02-23 18:22 UTC, amirziai approved these changes

2017-02-23 18:27 UTC, merged